SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


CREATE TABLE IF NOT EXISTS `USER` (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  EMAIL varchar(60) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  USERNAME varchar(50) NOT NULL,
  USERTYPE varchar(20) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY EMAIL (EMAIL)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1078 ;

CREATE TABLE IF NOT EXISTS `CLIENT` (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  ADDRESS varchar(255) NOT NULL,
  CITY varchar(50) NOT NULL,
  FIRSTNAME varchar(50) NOT NULL,
  GENDER varchar(8) NOT NULL,
  LASTNAME varchar(50) NOT NULL,
  PHONE varchar(15) NOT NULL,
  PINCODE varchar(7) NOT NULL,
  STATE varchar(50) NOT NULL,
  CL_USERID_ID bigint(20) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY(CL_USERID_ID) REFERENCES `USER`(ID)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=8 ;



CREATE TABLE IF NOT EXISTS ORGANIZATION (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  ORG_ADDRESS varchar(255) NOT NULL,
  ORG_ALTPHONE varchar(15) NOT NULL,
  ORG_CITY varchar(50) NOT NULL,
  ORG_NAME varchar(50) NOT NULL,
  ORG_PHONE varchar(15) NOT NULL,
  ORG_PINCODE varchar(7) NOT NULL,
  ORG_REGNO varchar(30) NOT NULL,
  ORG_STATE varchar(50) NOT NULL,
  ORG_USERID_ID bigint(20) NOT NULL,
  ORG_SECTOR varchar(10) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ORG_REGNO (ORG_REGNO),
  FOREIGN KEY(ORG_USERID_ID) REFERENCES `USER`(ID) 
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=18 ;



CREATE TABLE IF NOT EXISTS OFFICER (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  OFF_ADDRESS varchar(255) NOT NULL,
  OFF_DEPARTMENT varchar(50) NOT NULL,
  OFF_DESIGNATION varchar(50) NOT NULL,
  OFF_DOMAIN varchar(50) NOT NULL,
  OFF_FIRSTNAME varchar(50) NOT NULL,
  OFF_GENDER varchar(10) NOT NULL,
  OFF_KEYWORDS longtext NOT NULL,
  OFF_LASTNAME varchar(50) NOT NULL,
  OFF_PHONE varchar(15) NOT NULL,
  OFF_PINCODE varchar(7) NOT NULL,
  OFF_USERID_ID bigint(20) NOT NULL,
  OFF_ORG_ID bigint(20) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY(OFF_USERID_ID) REFERENCES `USER`(ID),
  FOREIGN KEY(OFF_ORG_ID) REFERENCES ORGANIZATION(ID)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=27 ;



CREATE TABLE IF NOT EXISTS GRIEVANCEREGISTRATION (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  GR_CITY varchar(50) NOT NULL,
  GR_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  GR_DESCRIPTION longtext NOT NULL,
  GR_LOCATION varchar(255) NOT NULL,
  GR_PICS varchar(255) DEFAULT NULL,
  GR_PINCODE varchar(7) NOT NULL,
  GR_SECTOR varchar(10) NOT NULL,
  GR_STATE varchar(50) NOT NULL,
  GR_CLIENT_ID bigint(20) NOT NULL,
  GR_ORGANIZATION_ID bigint(20) DEFAULT NULL,
  GR_OFFICER_ID bigint(20) DEFAULT NULL,
  GR_STATUS varchar(1) DEFAULT 'N',
  PRIMARY KEY (ID),
  FOREIGN KEY(GR_CLIENT_ID) REFERENCES CLIENT(ID),
  FOREIGN KEY(GR_ORGANIZATION_ID) REFERENCES ORGANIZATION(ID),
  FOREIGN KEY(GR_OFFICER_ID) REFERENCES OFFICER(ID)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=29 ;



CREATE TABLE IF NOT EXISTS GRIEVANCEREDRESSED (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  RG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  RG_MESSAGE varchar(255) NOT NULL,
  RG_TIMETAKEN varchar(10) NOT NULL,
  RG_GRIEVANCE_ID bigint(20) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY(RG_GRIEVANCE_ID) REFERENCES GRIEVANCEREGISTRATION(ID)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=8 ;


